version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - node_network
  node:
    build: .
    container_name: express
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - node_network
    volumes:
      - .:/app
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    build: ./config-nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/usr/local/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - node_network

networks:
  node_network:
